version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cheetah-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.production
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/static:/app/static
    depends_on:
      - frontend
    networks:
      - cheetah-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cheetah-frontend
    restart: always
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    networks:
      - cheetah-network

  nginx:
    image: nginx:alpine
    container_name: cheetah-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - cheetah-network

networks:
  cheetah-network:
    driver: bridge
