"""Add status field to Documents

Revision ID: 873741ad5e9b
Revises: ad484a8e0a13
Create Date: 2025-06-28 01:57:26.740699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873741ad5e9b'
down_revision = 'ad484a8e0a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite compatibility ###
    with op.batch_alter_table('Documents', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status',
                sa.String(length=50),
                nullable=False,
                server_default='uploaded',  # ✅ แก้ตรงนี้
                comment='Status of the document (e.g., uploaded, verified)'
            )
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Documents', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
